create table if not exists public.workspace_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  session_id text not null,
  title text not null default 'Eduvane Session',
  messages jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, session_id)
);

alter table public.workspace_history enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'workspace_history'
      and policyname = 'workspace_history_select_owner'
  ) then
    create policy "workspace_history_select_owner"
      on public.workspace_history
      for select
      using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'workspace_history'
      and policyname = 'workspace_history_insert_owner'
  ) then
    create policy "workspace_history_insert_owner"
      on public.workspace_history
      for insert
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'workspace_history'
      and policyname = 'workspace_history_update_owner'
  ) then
    create policy "workspace_history_update_owner"
      on public.workspace_history
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;
